### ISSUE TITLE
I got jdk 1.7 not 1.8

### ISSUE THREAD

**Issue by Yisaer** [pjfanning/docker-spark-jdk8#1]
I pulled your image and run the follow cmd

`docker run -d -h sandbox pjfanning/docker-spark-jdk8:1.6.2 -d`

and I exec **/bin/bash** into shell and run **java -version** to check the version

and here is the result

```
java version "1.7.0_101"
OpenJDK Runtime Environment (rhel-2.6.6.4.el6_8-x86_64 u101-b00)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)
```

**Comment by Yisaer** [comment]
and if run then follow cmd

`docker run -it -p 8088:8088 -p 8042:8042 -p 4040:4040 -p 9000:9000 -p 50070:50070 -p 8030-8033:8030-8033 -h sandbox pjfanning/docker-spark:1.6.2 bash
`
I got the jdk1.5

**Comment by pjfanning** [comment]
There was a mistake in the README - should be
`docker run -it -p 8088:8088 -p 8042:8042 -p 4040:4040 -p 9000:9000 -p 50070:50070 -p 8030-8033:8030-8033 -h sandbox pjfanning/docker-spark-jdk8:1.6.2 bash`

```
spark-shell \
--master yarn-client \
--driver-memory 1g \
--executor-memory 1g \
--executor-cores 1
```

Prints out a message saying
`Using Scala version 2.10.5 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_92)
Type in expressions to have them evaluated.
Type :help for more information.`
